window.XIAOHU_HOTSPOTS_DATA = {
  "meta": {
    "generated_at": "2026-08-22T02:12:23",
    "note": "Generated by scripts/collect_business_hotspots.py. Safe to overwrite."
  },
  "report": {
    "generated_at": "2026-08-22T02:12:23",
    "days": 15,
    "source_count": 6,
    "raw_item_count": 82,
    "hotspot_count": 15,
    "wechat_index_file": null,
    "kol_mentions_file": null,
    "video_sources_file": "data/video_sources.csv",
    "social_opinions_file": null,
    "errors": [],
    "outputs": {
      "csv": "20260822-021223-business-hotspots.csv",
      "json": "20260822-021223-business-hotspots.json",
      "raw": "20260822-021223-raw-items.json",
      "report": "20260822-021223-collection-report.json",
      "frontend_data": "hotspots-data.js"
    },
    "visible_raw_item_count": 20
  },
  "hotspots": [
    {
      "title": "宇树科技10日开启IPO申购 具身智能赛道迎来IPO密集期|深度",
      "source": "36氪；新浪财经；澎湃新闻；财联社",
      "date": "2026-08-19",
      "industry": "机器人行业",
      "type": "公司/行业动态",
      "summary": "人形机器人成本骤降九成，灵巧手融资暴涨1500% ，加速产业落地丨大咖星选 手机新浪网",
      "core_summary": "人形机器人成本骤降九成，灵巧手融资暴涨1500% ，加速产业落地丨大咖星选 手机新浪网 该事件涉及机器人行业头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-21：新浪财经报道/收录《雷军躺赚152亿：人形机器人的风口终于把投资人吹成了赢家》。",
        "2026-08-20：36氪报道/收录《复旦95后做机器人大脑，眸深智能融资3亿元》。",
        "2026-08-19：新浪财经报道/收录《人形机器人成本骤降九成，灵巧手融资暴涨1500% ，加速产业落地丨大咖星选》。",
        "2026-08-14：澎湃新闻报道/收录《宇树IPO狂欢背后：人形机器人“贫富悬殊”》。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 4 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从“为什么资本突然扎堆”切入，拆三件事：技术成熟度、工厂场景落地、上市窗口期。",
      "topic_value": "标题方向：人形机器人到底是产业爆发，还是资本抢跑。核心冲突：融资和上市热度很高，但真正量产、交付和商业回款仍需要验证。小胡讲法：从“为什么资本突然扎堆”切入，拆三件事：技术成熟度、工厂场景落地、上市窗口期。避坑：不要把演示视频等同于商业化，重点追问订单、成本和真实场景。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "低",
      "verification_status": "多源确认",
      "verification_note": "已有至少两个媒体渠道覆盖，可作为较稳定候选。",
      "media_channel_count": 4,
      "media_channels": "36氪、新浪财经、澎湃新闻、财联社",
      "media_items": [
        {
          "source": "澎湃新闻",
          "title": "宇树IPO狂欢背后：人形机器人“贫富悬殊”",
          "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE1TRDVTci1ScE11REpsbGhQNjFKc2JTazJiVjNwSk80RTd1RklqWkI3bjB5UW5LOEE5OWNYekhoQ2pJX3RITmhTMVlIVjRLblM2MWs4TEFDdlpva1BqVXc?oc=5",
          "date": "2026-08-14"
        },
        {
          "source": "新浪财经",
          "title": "人形机器人成本骤降九成，灵巧手融资暴涨1500% ，加速产业落地丨大咖星选",
          "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxPRWI1S1Q2ZXBvaWVvSUstWkx4LXkwV3VmVHF0TWZmZ2RodnRQT2gyQ1NNOFVmZVJNd2xqVUgzUU92YnhyLXpTMUZPRWxENnFMVklDMmN2Slc2SDBCTlAwUWdOUHdXUEV5ekloeEs3ZXFZcXBCcG9qWVZ2NXFtWVJPYTRR?oc=5",
          "date": "2026-08-19"
        },
        {
          "source": "财联社",
          "title": "宇树科技10日开启IPO申购 具身智能赛道迎来IPO密集期|深度",
          "url": "https://news.google.com/rss/articles/CBMiRkFVX3lxTE1NeWtaWm9ZZkZNV0duSl9ZUVJVRGFkSFoxbW83TTljNmhTa09SMW5BZHlyRE8tRHNXMk1qRmJRLTBxUDVfYVE?oc=5",
          "date": "2026-08-08"
        },
        {
          "source": "新浪财经",
          "title": "雷军躺赚152亿：人形机器人的风口终于把投资人吹成了赢家",
          "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE1RSFFKYUI2WTc4b2w2eURwVTQ0REFERURsM3ltdmVudzFra0tBVDFmOGpsenV5bDVMblpHTzhocW1BSDUwaHVOaGZ0eXlRMmpFQ1pkTmJJUk10RzlQbWNadXdOREVZby0tT3cySkRsSHgyQQ?oc=5",
          "date": "2026-08-21"
        },
        {
          "source": "36氪",
          "title": "复旦95后做机器人大脑，眸深智能融资3亿元",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1SSEh4QkRJbVRPMktCNDloNlhacmJxMGg4dkl0cWM1V3czMXZqNy1DczN3Mi1rWm9Zb290UjhkQS01OGNOdzRJbHBla3p4dw?oc=5",
          "date": "2026-08-20"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 43,
      "confidence_reason": "置信度 43/100，依据：4 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 5.2,
      "businessValue": 8.9,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "短",
      "note": "待核查来源：澎湃新闻: https://news.google.com/rss/articles/CBMiXkFVX3lxTE1TRDVTci1ScE11REpsbGhQNjFKc2JTazJiVjNwSk80RTd1RklqWkI3bjB5UW5LOEE5OWNYekhoQ2pJX3RITmhTMVlIVjRLblM2MWs4TEFDdlpva1BqVXc?oc=5 | 新浪财经: https://news.google.com/rss/articles/CBMiggFBVV95cUxPRWI1S1Q2ZXBvaWVvSUstWkx4LXkwV3VmVHF0TWZmZ2RodnRQT2gyQ1NNOFVmZVJNd2xqVUgzUU92YnhyLXpTMUZPRWxENnFMVklDMmN2Slc2SDBCTlAwUWdOUHdXUEV5ekloeEs3ZXFZcXBCcG9qWVZ2NXFtWVJPYTRR?oc=5 | 财联社: https://news.google.com/rss/articles/CBMiRkFVX3lxTE1NeWtaWm9ZZkZNV0duSl9ZUVJVRGFkSFoxbW83TTljNmhTa09SMW5BZHlyRE8tRHNXMk1qRmJRLTBxUDVfYVE?oc=5"
    },
    {
      "title": "多家投行看好阿里最新财报：AI资本开支进入“回报验证期”",
      "source": "新浪财经；界面新闻",
      "date": "2026-08-20",
      "industry": "AI与芯片行业",
      "type": "财报",
      "summary": "650家客户上车！阿里吴泳铭：平头哥AI芯片下半年将持续放量 新浪财经",
      "core_summary": "650家客户上车！阿里吴泳铭：平头哥AI芯片下半年将持续放量 新浪财经 该事件涉及AI与芯片行业头部公司或知名平台的财报，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-20：新浪财经报道/收录《650家客户上车！阿里吴泳铭：平头哥AI芯片下半年将持续放量》。",
        "时间未记录：界面新闻报道/收录《多家投行看好阿里最新财报：AI资本开支进入“回报验证期”》。",
        "事件类型被归类为财报，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 2 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "把阿里、腾讯、京东放在一张表里讲：谁用 AI 拉云收入，谁用外卖换用户频次，谁在用利润换未来入口。",
      "topic_value": "标题方向：大厂财报都在说 AI，但真正的问题是利润去哪了。核心冲突：收入增长、AI 投入和新业务烧钱同时发生，资本市场关心的是 AI 何时从故事变成利润。小胡讲法：把阿里、腾讯、京东放在一张表里讲：谁用 AI 拉云收入，谁用外卖换用户频次，谁在用利润换未来入口。避坑：避免堆财报数字，必须把指标翻译成一句商业判断：增长质量、利润压力和下一轮入口下注。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "低",
      "verification_status": "多源确认",
      "verification_note": "已有至少两个媒体渠道覆盖，可作为较稳定候选。",
      "media_channel_count": 2,
      "media_channels": "新浪财经、界面新闻",
      "media_items": [
        {
          "source": "界面新闻",
          "title": "多家投行看好阿里最新财报：AI资本开支进入“回报验证期”",
          "url": "https://www.jiemian.com/article/14964748.html",
          "date": ""
        },
        {
          "source": "新浪财经",
          "title": "650家客户上车！阿里吴泳铭：平头哥AI芯片下半年将持续放量",
          "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxOTTcwQlhhMDZkVFRnd1hhcHlCSDdsZmcwSVNIdm9DTTdlUXE4Rmc4aEJBTzlPbHlqTjd6VDJibjBRZzNQUkVhcmpzNS1Ma2tGSHk1VC04NFR6anNwdTRCTE5NX09NV3NUeGJub3VScGFrSnluR1o0QTNYM1hQMmJJMkNHbzUyRFpLR21zMlRHcG0zYWpY?oc=5",
          "date": "2026-08-20"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 32,
      "confidence_reason": "置信度 32/100，依据：2 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 2.2,
      "businessValue": 7.4,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 7.1,
      "volume": "短",
      "note": "待核查来源：界面新闻: https://www.jiemian.com/article/14964748.html | 新浪财经: https://news.google.com/rss/articles/CBMilAFBVV95cUxOTTcwQlhhMDZkVFRnd1hhcHlCSDdsZmcwSVNIdm9DTTdlUXE4Rmc4aEJBTzlPbHlqTjd6VDJibjBRZzNQUkVhcmpzNS1Ma2tGSHk1VC04NFR6anNwdTRCTE5NX09NV3NUeGJub3VScGFrSnluR1o0QTNYM1hQMmJJMkNHbzUyRFpLR21zMlRHcG0zYWpY?oc=5"
    },
    {
      "title": "估值366亿，AI视频独角兽又融资，英特尔投了",
      "source": "36氪",
      "date": "2026-08-17",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "估值366亿，AI视频独角兽又融资，英特尔投了 36 Kr",
      "core_summary": "估值366亿，AI视频独角兽又融资，英特尔投了 36 Kr 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-17：36氪报道/收录《估值366亿，AI视频独角兽又融资，英特尔投了》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：估值366亿准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "估值366亿，AI视频独角兽又融资，英特尔投了",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5wRG1ZZDJlYVJKVnFJaU5jRW01TjJDYTF3QWtzTDFXLWExRzdaWHNYRnBuM1F5ZUNqZnN6UzJGZndFM0k0anhQMG1GT0FtZw?oc=5",
          "date": "2026-08-17"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 3.2,
      "businessValue": 7.5,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE5wRG1ZZDJlYVJKVnFJaU5jRW01TjJDYTF3QWtzTDFXLWExRzdaWHNYRnBuM1F5ZUNqZnN6UzJGZndFM0k0anhQMG1GT0FtZw?oc=5"
    },
    {
      "title": "财报公告 | AI云、昆仑芯、萝卜快跑多点突破，百度推进双重上市",
      "source": "财新网",
      "date": "2026-08-22",
      "industry": "全球科技与资本市场",
      "type": "财报",
      "summary": "财报公告 | AI云、昆仑芯、萝卜快跑多点突破，百度推进双重上市。该事件属于全球科技与资本市场的财报，需要结合公司动作、行业格局和商业模式变化判断选题价值。",
      "core_summary": "财报公告 | AI云、昆仑芯、萝卜快跑多点突破，百度推进双重上市。该事件属于全球科技与资本市场的财报，需要结合公司动作、行业格局和商业模式变化判断选题价值。 该事件涉及全球科技与资本市场头部公司或知名平台的财报，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "时间未记录：财新网报道/收录《财报公告 | AI云、昆仑芯、萝卜快跑多点突破，百度推进双重上市》。",
        "事件类型被归类为财报，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：财报公告准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "财新网",
      "media_items": [
        {
          "source": "财新网",
          "title": "财报公告 | AI云、昆仑芯、萝卜快跑多点突破，百度推进双重上市",
          "url": "https://promote.caixin.com/2026-08-19/102475650.html",
          "date": ""
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 21,
      "confidence_reason": "置信度 21/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 3.0,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：财新网: https://promote.caixin.com/2026-08-19/102475650.html"
    },
    {
      "title": "28家具身独角兽估值超3500亿元，谁是下一个宇树？",
      "source": "澎湃新闻",
      "date": "2026-08-19",
      "industry": "机器人行业",
      "type": "公司/行业动态",
      "summary": "28家具身独角兽估值超3500亿元，谁是下一个宇树？ thepaper.cn",
      "core_summary": "28家具身独角兽估值超3500亿元，谁是下一个宇树？ thepaper.cn 该事件涉及机器人行业头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-19：澎湃新闻报道/收录《28家具身独角兽估值超3500亿元，谁是下一个宇树？》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从一个具体使用场景切入，解释机器人公司要跨过演示、试点、批量交付和售后维护四道门槛。",
      "topic_value": "标题方向：宇树火起来以后，机器人离真实赚钱还有多远。核心冲突：展示和融资带来想象力，但量产成本、稳定交付和真实场景订单才决定公司能否穿越热度。小胡讲法：从一个具体使用场景切入，解释机器人公司要跨过演示、试点、批量交付和售后维护四道门槛。避坑：不要把发布会视频和样机演示等同于规模商业化，重点核对订单、价格和交付对象。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "澎湃新闻",
      "media_items": [
        {
          "source": "澎湃新闻",
          "title": "28家具身独角兽估值超3500亿元，谁是下一个宇树？",
          "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE1oQTFaek9EUDhTTHNKY1hNc1NkdHdYNTJ3UWJCQWZEcTRnNVhFMk90VkFZNXF5Y0RuVjlhSldyRkxWUW9RcHRWQjRhdzRGTDExRjdXRGFPNWtKTUtCN0E?oc=5",
          "date": "2026-08-19"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 3.0,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：澎湃新闻: https://news.google.com/rss/articles/CBMiXkFVX3lxTE1oQTFaek9EUDhTTHNKY1hNc1NkdHdYNTJ3UWJCQWZEcTRnNVhFMk90VkFZNXF5Y0RuVjlhSldyRkxWUW9RcHRWQjRhdzRGTDExRjdXRGFPNWtKTUtCN0E?oc=5"
    },
    {
      "title": "贵州茅台回应利润下滑、飞天茅台提价等问题",
      "source": "财新网",
      "date": "2026-08-22",
      "industry": "消费与新零售行业",
      "type": "财报",
      "summary": "贵州茅台回应利润下滑、飞天茅台提价等问题。该事件属于消费与新零售行业的财报，需要结合公司动作、行业格局和商业模式变化判断选题价值。",
      "core_summary": "贵州茅台回应利润下滑、飞天茅台提价等问题。该事件属于消费与新零售行业的财报，需要结合公司动作、行业格局和商业模式变化判断选题价值。 该事件涉及消费与新零售行业头部公司或知名平台的财报，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "时间未记录：财新网报道/收录《贵州茅台回应利润下滑、飞天茅台提价等问题》。",
        "事件类型被归类为财报，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通消费者的一笔账切入，讲价格、渠道、供应链和品牌故事如何共同决定这门生意能不能持续。",
      "topic_value": "标题方向：贵州茅台回应利润下滑、飞天茅台提价等...的热度背后，是品牌溢价还是消费降级。核心冲突：消费者一边追求情绪价值和性价比，一边对涨价、缩水、排队和黄牛更敏感，品牌增长很容易转成信任考验。小胡讲法：从普通消费者的一笔账切入，讲价格、渠道、供应链和品牌故事如何共同决定这门生意能不能持续。避坑：不要把社交平台热度等同于真实复购，也不要用个别门店或个别商品代表整个品牌。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "财新网",
      "media_items": [
        {
          "source": "财新网",
          "title": "贵州茅台回应利润下滑、飞天茅台提价等问题",
          "url": "https://www.caixin.com/2026-08-21/102476619.html",
          "date": ""
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 21,
      "confidence_reason": "置信度 21/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 1.4,
      "businessValue": 7.1,
      "controversy": 5.7,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：财新网: https://www.caixin.com/2026-08-21/102476619.html"
    },
    {
      "title": "年入47亿，92年字节前员工做出200亿AI独角兽，冲刺港股IPO",
      "source": "36氪",
      "date": "2026-08-17",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "年入47亿，92年字节前员工做出200亿AI独角兽，冲刺港股IPO 36 Kr",
      "core_summary": "年入47亿，92年字节前员工做出200亿AI独角兽，冲刺港股IPO 36 Kr 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-17：36氪报道/收录《年入47亿，92年字节前员工做出200亿AI独角兽，冲刺港股IPO》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：字节准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "年入47亿，92年字节前员工做出200亿AI独角兽，冲刺港股IPO",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1CVGRZOTRMS0E4Ulk2N0RSSU9mRHdWWWdjWE1IZ0xtZUM2SXAwUkk4eUdleFZTbXZoUklsUlY0dnJRNU55MFVLSHVGZUhUdw?oc=5",
          "date": "2026-08-17"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 3.8,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE1CVGRZOTRMS0E4Ulk2N0RSSU9mRHdWWWdjWE1IZ0xtZUM2SXAwUkk4eUdleFZTbXZoUklsUlY0dnJRNU55MFVLSHVGZUhUdw?oc=5"
    },
    {
      "title": "“围猎”IPO手法层出不穷 香港ZD Group爆发兑付危机(含视频)",
      "source": "财新网",
      "date": "2026-08-22",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "“围猎”IPO手法层出不穷 香港ZD Group爆发兑付危机(含视频)。该事件属于全球科技与资本市场的公司/行业动态，需要结合公司动作、行业格局和商业模式变化判断选题价值。",
      "core_summary": "“围猎”IPO手法层出不穷 香港ZD Group爆发兑付危机(含视频)。该事件属于全球科技与资本市场的公司/行业动态，需要结合公司动作、行业格局和商业模式变化判断选题价值。 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "时间未记录：财新网报道/收录《“围猎”IPO手法层出不穷 香港ZD Group爆发兑付危机(含视频)》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：“围猎”IPO手法层出不穷 香港ZD...准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "财新网",
      "media_items": [
        {
          "source": "财新网",
          "title": "“围猎”IPO手法层出不穷 香港ZD Group爆发兑付危机(含视频)",
          "url": "https://finance.caixin.com/2026-08-18/102475000.html",
          "date": ""
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 21,
      "confidence_reason": "置信度 21/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 0.8,
      "businessValue": 7.1,
      "controversy": 5.7,
      "longevity": 5.7,
      "fit": 6.0,
      "volume": "中",
      "note": "待核查来源：财新网: https://finance.caixin.com/2026-08-18/102475000.html"
    },
    {
      "title": "李宁2026中报：营收增长2.8%达152.4亿，稳健经营，积极布局运动资源",
      "source": "界面新闻",
      "date": "2026-08-22",
      "industry": "消费与新零售行业",
      "type": "财报",
      "summary": "李宁2026中报：营收增长2.8%达152.4亿，稳健经营，积极布局运动资源。该事件属于消费与新零售行业的财报，需要结合公司动作、行业格局和商业模式变化判断选题价值。",
      "core_summary": "李宁2026中报：营收增长2.8%达152.4亿，稳健经营，积极布局运动资源。该事件属于消费与新零售行业的财报，需要结合公司动作、行业格局和商业模式变化判断选题价值。 该事件涉及消费与新零售行业头部公司或知名平台的财报，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "时间未记录：界面新闻报道/收录《李宁2026中报：营收增长2.8%达152.4亿，稳健经营，积极布局运动资源》。",
        "事件类型被归类为财报，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通消费者的一笔账切入，讲价格、渠道、供应链和品牌故事如何共同决定这门生意能不能持续。",
      "topic_value": "标题方向：李宁的热度背后，是品牌溢价还是消费降级。核心冲突：消费者一边追求情绪价值和性价比，一边对涨价、缩水、排队和黄牛更敏感，品牌增长很容易转成信任考验。小胡讲法：从普通消费者的一笔账切入，讲价格、渠道、供应链和品牌故事如何共同决定这门生意能不能持续。避坑：不要把社交平台热度等同于真实复购，也不要用个别门店或个别商品代表整个品牌。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "界面新闻",
      "media_items": [
        {
          "source": "界面新闻",
          "title": "李宁2026中报：营收增长2.8%达152.4亿，稳健经营，积极布局运动资源",
          "url": "https://www.jiemian.com/article/14960481.html",
          "date": ""
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 1.4,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：界面新闻: https://www.jiemian.com/article/14960481.html"
    },
    {
      "title": "超越马斯克，史上最大IPO要来了",
      "source": "36氪",
      "date": "2026-08-16",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "超越马斯克，史上最大IPO要来了 36 Kr",
      "core_summary": "超越马斯克，史上最大IPO要来了 36 Kr 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-16：36氪报道/收录《超越马斯克，史上最大IPO要来了》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：超越马斯克准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "超越马斯克，史上最大IPO要来了",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5YNGV1TFM1YzFCS3otNTEyZkxGb0UyT0VhUU0tZGp2d2c1TnBUazVXSGt4dE8zZmhQNE9ycnp2dGpGenp0ZnpsaFZCRGlsdw?oc=5",
          "date": "2026-08-16"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 2.2,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE5YNGV1TFM1YzFCS3otNTEyZkxGb0UyT0VhUU0tZGp2d2c1TnBUazVXSGt4dE8zZmhQNE9ycnp2dGpGenp0ZnpsaFZCRGlsdw?oc=5"
    },
    {
      "title": "QuickBooks竞品初创企业估值纷纷达到10亿美元",
      "source": "新浪财经",
      "date": "2026-08-19",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "QuickBooks竞品初创企业估值纷纷达到10亿美元 新浪财经",
      "core_summary": "QuickBooks竞品初创企业估值纷纷达到10亿美元 新浪财经 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-19：新浪财经报道/收录《QuickBooks竞品初创企业估值纷纷达到10亿美元》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：QuickBooks竞品初创企业估值...准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "新浪财经",
      "media_items": [
        {
          "source": "新浪财经",
          "title": "QuickBooks竞品初创企业估值纷纷达到10亿美元",
          "url": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxOQ2tjVlpNajJpRTAtMml2UHR6TmppQ0RvV2dNS3ZnSTVDbjZWY2NqOFZEYThUbWsyclZPMS1Wd3YyVGJnYnIzV3ZUUzlaNExkblBoM09rNFExZzFqMGgzWXNOUE5HVEFPSE9LNzdCVXI5a3VCaVdrQ0lhQVlrdFZHbVlVNDdKQWJfYjgwNUtGQUZ2YUF3eXQ1c1B1NExMeExnU2ZhdGJaelhNcUxSWU5iN3I1dWI2Z0w0bmFJMmZfSXBxdlc5T0dLWElnYTZOcWF4M1BRdnlKQUV1SXA0LXZr?oc=5",
          "date": "2026-08-19"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 0.8,
      "businessValue": 7.0,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：新浪财经: https://news.google.com/rss/articles/CBMi3wFBVV95cUxOQ2tjVlpNajJpRTAtMml2UHR6TmppQ0RvV2dNS3ZnSTVDbjZWY2NqOFZEYThUbWsyclZPMS1Wd3YyVGJnYnIzV3ZUUzlaNExkblBoM09rNFExZzFqMGgzWXNOUE5HVEFPSE9LNzdCVXI5a3VCaVdrQ0lhQVlrdFZHbVlVNDdKQWJfYjgwNUtGQUZ2YUF3eXQ1c1B1NExMeExnU2ZhdGJaelhNcUxSWU5iN3I1dWI2Z0w0bmFJMmZfSXBxdlc5T0dLWElnYTZOcWF4M1BRdnlKQUV1SXA0LXZr?oc=5"
    },
    {
      "title": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”",
      "source": "36氪",
      "date": "2026-08-19",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血” 36 Kr",
      "core_summary": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血” 36 Kr 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-19：36氪报道/收录《4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：4万亿美元准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE4wTWRQSnMxSmZBU2dlTmg3YVdHNzh5UDd4SDVCMjYwZDBRa3RFdEg0UjUyVVBOeHlwenJTSnREc0czX1lrTHc1cGZaVkhLQQ?oc=5",
          "date": "2026-08-19"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 1.6,
      "businessValue": 6.7,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE4wTWRQSnMxSmZBU2dlTmg3YVdHNzh5UDd4SDVCMjYwZDBRa3RFdEg0UjUyVVBOeHlwenJTSnREc0czX1lrTHc1cGZaVkhLQQ?oc=5"
    },
    {
      "title": "葛小波辞任国联民生证券总裁 7年间完成上市及民生证券并购",
      "source": "财新网",
      "date": "2026-08-22",
      "industry": "全球科技与资本市场",
      "type": "公司战略",
      "summary": "葛小波辞任国联民生证券总裁 7年间完成上市及民生证券并购。该事件属于全球科技与资本市场的公司战略，需要结合公司动作、行业格局和商业模式变化判断选题价值。",
      "core_summary": "葛小波辞任国联民生证券总裁 7年间完成上市及民生证券并购。该事件属于全球科技与资本市场的公司战略，需要结合公司动作、行业格局和商业模式变化判断选题价值。 该事件涉及全球科技与资本市场头部公司或知名平台的公司战略，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "时间未记录：财新网报道/收录《葛小波辞任国联民生证券总裁 7年间完成上市及民生证券并购》。",
        "事件类型被归类为公司战略，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：葛小波辞任国联民生证券总裁 7年间完...准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "财新网",
      "media_items": [
        {
          "source": "财新网",
          "title": "葛小波辞任国联民生证券总裁 7年间完成上市及民生证券并购",
          "url": "https://finance.caixin.com/2026-08-21/102476700.html",
          "date": ""
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 21,
      "confidence_reason": "置信度 21/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 0.8,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "中",
      "note": "待核查来源：财新网: https://finance.caixin.com/2026-08-21/102476700.html"
    },
    {
      "title": "Anthropic最快十月上市估值2万亿美元 超越SpaceX刷新IPO纪录",
      "source": "虎嗅",
      "date": "2026-08-15",
      "industry": "AI与芯片行业",
      "type": "公司/行业动态",
      "summary": "Anthropic最快十月上市估值2万亿美元 超越SpaceX刷新IPO纪录 虎嗅",
      "core_summary": "Anthropic最快十月上市估值2万亿美元 超越SpaceX刷新IPO纪录 虎嗅 该事件涉及AI与芯片行业头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-15：虎嗅报道/收录《Anthropic最快十月上市估值2万亿美元 超越SpaceX刷新IPO纪录》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "用“谁付钱、谁省钱、谁被替代”三问切入，把复杂技术翻译成商业账本。",
      "topic_value": "标题方向：Anthropic的 AI 故事，最后要落到成本还是收入。核心冲突：市场愿意为 AI 想象力买单，但企业必须证明算力、芯片或模型投入能转化为订单、利润和用户效率。小胡讲法：用“谁付钱、谁省钱、谁被替代”三问切入，把复杂技术翻译成商业账本。避坑：不要展开过多技术细节，也不要把概念热度直接等同于商业化落地。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "待核验",
      "verification_note": "单一媒体来源，且包含上市/融资/估值类不确定表述，适合先观察，不建议直接作为确定事实讲。",
      "media_channel_count": 1,
      "media_channels": "虎嗅",
      "media_items": [
        {
          "source": "虎嗅",
          "title": "Anthropic最快十月上市估值2万亿美元 超越SpaceX刷新IPO纪录",
          "url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTFBMY3dLZW1oaExMVjBiUDRmVU5NY0RSaTNzOF9mczhrbmRpd094OGc3YXNCYTgwcTZjbEVyb29NSWlBRG05T0l3aUxlYWRSSG5PcTgySA?oc=5",
          "date": "2026-08-15"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 8,
      "confidence_reason": "置信度 8/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中，待核验。",
      "public_interest": 5.7,
      "businessValue": 7.5,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：虎嗅: https://news.google.com/rss/articles/CBMiVEFVX3lxTFBMY3dLZW1oaExMVjBiUDRmVU5NY0RSaTNzOF9mczhrbmRpd094OGc3YXNCYTgwcTZjbEVyb29NSWlBRG05T0l3aUxlYWRSSG5PcTgySA?oc=5"
    },
    {
      "title": "清华系AI视频独角兽拟赴港IPO",
      "source": "36氪",
      "date": "2026-08-19",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "清华系AI视频独角兽拟赴港IPO 36 Kr",
      "core_summary": "清华系AI视频独角兽拟赴港IPO 36 Kr 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-08-19：36氪报道/收录《清华系AI视频独角兽拟赴港IPO》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：清华系AI视频独角兽拟赴港IPO准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "待核验",
      "verification_note": "单一媒体来源，且包含上市/融资/估值类不确定表述，适合先观察，不建议直接作为确定事实讲。",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "清华系AI视频独角兽拟赴港IPO",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9wWHBzbFBFTlVlT3JXOUYzMml1RnRON0ZHREZqVXYxV1k3cm5KYWhiRjFKQUhzVU94X0JSaEVGSkxqdGF5NzBVek9LVWtIdw?oc=5",
          "date": "2026-08-19"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 8,
      "confidence_reason": "置信度 8/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中，待核验。",
      "public_interest": 2.4,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE9wWHBzbFBFTlVlT3JXOUYzMml1RnRON0ZHREZqVXYxV1k3cm5KYWhiRjFKQUhzVU94X0JSaEVGSkxqdGF5NzBVek9LVWtIdw?oc=5"
    }
  ],
  "rawItems": [
    {
      "source_name": "界面新闻",
      "title": "多家投行看好阿里最新财报：AI资本开支进入“回报验证期”",
      "url": "https://www.jiemian.com/article/14964748.html",
      "published": "",
      "summary": "",
      "source_weight": 1.0
    },
    {
      "source_name": "界面新闻",
      "title": "李宁2026中报：营收增长2.8%达152.4亿，稳健经营，积极布局运动资源",
      "url": "https://www.jiemian.com/article/14960481.html",
      "published": "",
      "summary": "",
      "source_weight": 1.0
    },
    {
      "source_name": "财新网",
      "title": "葛小波辞任国联民生证券总裁 7年间完成上市及民生证券并购",
      "url": "https://finance.caixin.com/2026-08-21/102476700.html",
      "published": "",
      "summary": "",
      "source_weight": 1.15
    },
    {
      "source_name": "财新网",
      "title": "“围猎”IPO手法层出不穷 香港ZD Group爆发兑付危机(含视频)",
      "url": "https://finance.caixin.com/2026-08-18/102475000.html",
      "published": "",
      "summary": "",
      "source_weight": 1.15
    },
    {
      "source_name": "财新网",
      "title": "贵州茅台回应利润下滑、飞天茅台提价等问题",
      "url": "https://www.caixin.com/2026-08-21/102476619.html",
      "published": "",
      "summary": "",
      "source_weight": 1.15
    },
    {
      "source_name": "财新网",
      "title": "财报公告 | AI云、昆仑芯、萝卜快跑多点突破，百度推进双重上市",
      "url": "https://promote.caixin.com/2026-08-19/102475650.html",
      "published": "",
      "summary": "",
      "source_weight": 1.15
    },
    {
      "source_name": "澎湃新闻",
      "title": "28家具身独角兽估值超3500亿元，谁是下一个宇树？",
      "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE1oQTFaek9EUDhTTHNKY1hNc1NkdHdYNTJ3UWJCQWZEcTRnNVhFMk90VkFZNXF5Y0RuVjlhSldyRkxWUW9RcHRWQjRhdzRGTDExRjdXRGFPNWtKTUtCN0E?oc=5",
      "published": "2026-08-19",
      "summary": "28家具身独角兽估值超3500亿元，谁是下一个宇树？ thepaper.cn",
      "source_weight": 1.0
    },
    {
      "source_name": "36氪",
      "title": "年入47亿，92年字节前员工做出200亿AI独角兽，冲刺港股IPO",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1CVGRZOTRMS0E4Ulk2N0RSSU9mRHdWWWdjWE1IZ0xtZUM2SXAwUkk4eUdleFZTbXZoUklsUlY0dnJRNU55MFVLSHVGZUhUdw?oc=5",
      "published": "2026-08-17",
      "summary": "年入47亿，92年字节前员工做出200亿AI独角兽，冲刺港股IPO 36 Kr",
      "source_weight": 1.05
    },
    {
      "source_name": "虎嗅",
      "title": "Anthropic最快十月上市估值2万亿美元 超越SpaceX刷新IPO纪录",
      "url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTFBMY3dLZW1oaExMVjBiUDRmVU5NY0RSaTNzOF9mczhrbmRpd094OGc3YXNCYTgwcTZjbEVyb29NSWlBRG05T0l3aUxlYWRSSG5PcTgySA?oc=5",
      "published": "2026-08-15",
      "summary": "Anthropic最快十月上市估值2万亿美元 超越SpaceX刷新IPO纪录 虎嗅",
      "source_weight": 1.0
    },
    {
      "source_name": "36氪",
      "title": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE4wTWRQSnMxSmZBU2dlTmg3YVdHNzh5UDd4SDVCMjYwZDBRa3RFdEg0UjUyVVBOeHlwenJTSnREc0czX1lrTHc1cGZaVkhLQQ?oc=5",
      "published": "2026-08-19",
      "summary": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血” 36 Kr",
      "source_weight": 1.05
    },
    {
      "source_name": "澎湃新闻",
      "title": "宇树IPO狂欢背后：人形机器人“贫富悬殊”",
      "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE1TRDVTci1ScE11REpsbGhQNjFKc2JTazJiVjNwSk80RTd1RklqWkI3bjB5UW5LOEE5OWNYekhoQ2pJX3RITmhTMVlIVjRLblM2MWs4TEFDdlpva1BqVXc?oc=5",
      "published": "2026-08-14",
      "summary": "宇树IPO狂欢背后：人形机器人“贫富悬殊” thepaper.cn",
      "source_weight": 1.0
    },
    {
      "source_name": "36氪",
      "title": "清华系AI视频独角兽拟赴港IPO",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9wWHBzbFBFTlVlT3JXOUYzMml1RnRON0ZHREZqVXYxV1k3cm5KYWhiRjFKQUhzVU94X0JSaEVGSkxqdGF5NzBVek9LVWtIdw?oc=5",
      "published": "2026-08-19",
      "summary": "清华系AI视频独角兽拟赴港IPO 36 Kr",
      "source_weight": 1.05
    },
    {
      "source_name": "36氪",
      "title": "超越马斯克，史上最大IPO要来了",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5YNGV1TFM1YzFCS3otNTEyZkxGb0UyT0VhUU0tZGp2d2c1TnBUazVXSGt4dE8zZmhQNE9ycnp2dGpGenp0ZnpsaFZCRGlsdw?oc=5",
      "published": "2026-08-16",
      "summary": "超越马斯克，史上最大IPO要来了 36 Kr",
      "source_weight": 1.05
    },
    {
      "source_name": "新浪财经",
      "title": "QuickBooks竞品初创企业估值纷纷达到10亿美元",
      "url": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxOQ2tjVlpNajJpRTAtMml2UHR6TmppQ0RvV2dNS3ZnSTVDbjZWY2NqOFZEYThUbWsyclZPMS1Wd3YyVGJnYnIzV3ZUUzlaNExkblBoM09rNFExZzFqMGgzWXNOUE5HVEFPSE9LNzdCVXI5a3VCaVdrQ0lhQVlrdFZHbVlVNDdKQWJfYjgwNUtGQUZ2YUF3eXQ1c1B1NExMeExnU2ZhdGJaelhNcUxSWU5iN3I1dWI2Z0w0bmFJMmZfSXBxdlc5T0dLWElnYTZOcWF4M1BRdnlKQUV1SXA0LXZr?oc=5",
      "published": "2026-08-19",
      "summary": "QuickBooks竞品初创企业估值纷纷达到10亿美元 新浪财经",
      "source_weight": 0.95
    },
    {
      "source_name": "36氪",
      "title": "估值366亿，AI视频独角兽又融资，英特尔投了",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5wRG1ZZDJlYVJKVnFJaU5jRW01TjJDYTF3QWtzTDFXLWExRzdaWHNYRnBuM1F5ZUNqZnN6UzJGZndFM0k0anhQMG1GT0FtZw?oc=5",
      "published": "2026-08-17",
      "summary": "估值366亿，AI视频独角兽又融资，英特尔投了 36 Kr",
      "source_weight": 1.05
    },
    {
      "source_name": "新浪财经",
      "title": "人形机器人成本骤降九成，灵巧手融资暴涨1500% ，加速产业落地丨大咖星选",
      "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxPRWI1S1Q2ZXBvaWVvSUstWkx4LXkwV3VmVHF0TWZmZ2RodnRQT2gyQ1NNOFVmZVJNd2xqVUgzUU92YnhyLXpTMUZPRWxENnFMVklDMmN2Slc2SDBCTlAwUWdOUHdXUEV5ekloeEs3ZXFZcXBCcG9qWVZ2NXFtWVJPYTRR?oc=5",
      "published": "2026-08-19",
      "summary": "人形机器人成本骤降九成，灵巧手融资暴涨1500% ，加速产业落地丨大咖星选 手机新浪网",
      "source_weight": 0.95
    },
    {
      "source_name": "新浪财经",
      "title": "650家客户上车！阿里吴泳铭：平头哥AI芯片下半年将持续放量",
      "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxOTTcwQlhhMDZkVFRnd1hhcHlCSDdsZmcwSVNIdm9DTTdlUXE4Rmc4aEJBTzlPbHlqTjd6VDJibjBRZzNQUkVhcmpzNS1Ma2tGSHk1VC04NFR6anNwdTRCTE5NX09NV3NUeGJub3VScGFrSnluR1o0QTNYM1hQMmJJMkNHbzUyRFpLR21zMlRHcG0zYWpY?oc=5",
      "published": "2026-08-20",
      "summary": "650家客户上车！阿里吴泳铭：平头哥AI芯片下半年将持续放量 新浪财经",
      "source_weight": 0.95
    },
    {
      "source_name": "财联社",
      "title": "宇树科技10日开启IPO申购 具身智能赛道迎来IPO密集期|深度",
      "url": "https://news.google.com/rss/articles/CBMiRkFVX3lxTE1NeWtaWm9ZZkZNV0duSl9ZUVJVRGFkSFoxbW83TTljNmhTa09SMW5BZHlyRE8tRHNXMk1qRmJRLTBxUDVfYVE?oc=5",
      "published": "2026-08-08",
      "summary": "宇树科技10日开启IPO申购 具身智能赛道迎来IPO密集期|深度 财联社",
      "source_weight": 1.02
    },
    {
      "source_name": "新浪财经",
      "title": "雷军躺赚152亿：人形机器人的风口终于把投资人吹成了赢家",
      "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE1RSFFKYUI2WTc4b2w2eURwVTQ0REFERURsM3ltdmVudzFra0tBVDFmOGpsenV5bDVMblpHTzhocW1BSDUwaHVOaGZ0eXlRMmpFQ1pkTmJJUk10RzlQbWNadXdOREVZby0tT3cySkRsSHgyQQ?oc=5",
      "published": "2026-08-21",
      "summary": "雷军躺赚152亿：人形机器人的风口终于把投资人吹成了赢家 手机新浪网",
      "source_weight": 0.95
    },
    {
      "source_name": "36氪",
      "title": "复旦95后做机器人大脑，眸深智能融资3亿元",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1SSEh4QkRJbVRPMktCNDloNlhacmJxMGg4dkl0cWM1V3czMXZqNy1DczN3Mi1rWm9Zb290UjhkQS01OGNOdzRJbHBla3p4dw?oc=5",
      "published": "2026-08-20",
      "summary": "复旦95后做机器人大脑，眸深智能融资3亿元 36 Kr",
      "source_weight": 1.05
    }
  ]
};
