window.XIAOHU_HOTSPOTS_DATA = {
  "meta": {
    "generated_at": "2026-09-17T05:40:43",
    "note": "Generated by scripts/collect_business_hotspots.py. Safe to overwrite."
  },
  "report": {
    "generated_at": "2026-09-17T05:40:43",
    "days": 15,
    "source_count": 6,
    "raw_item_count": 82,
    "hotspot_count": 11,
    "wechat_index_file": null,
    "kol_mentions_file": null,
    "video_sources_file": "data/video_sources.csv",
    "social_opinions_file": null,
    "errors": [],
    "outputs": {
      "csv": "20260917-054043-business-hotspots.csv",
      "json": "20260917-054043-business-hotspots.json",
      "raw": "20260917-054043-raw-items.json",
      "report": "20260917-054043-collection-report.json",
      "frontend_data": "hotspots-data.js"
    },
    "visible_raw_item_count": 15
  },
  "hotspots": [
    {
      "title": "人形机器人量产分水岭：双巨头跨万台大关 百亿独角兽加速追赶",
      "source": "36氪；新浪财经",
      "date": "2026-09-09",
      "industry": "机器人行业",
      "type": "政策",
      "summary": "清华博士做具身大脑拿下九轮融资，他说机器人行业不存在所谓ChatGPT时刻｜硬氪专访 36氪",
      "core_summary": "清华博士做具身大脑拿下九轮融资，他说机器人行业不存在所谓ChatGPT时刻｜硬氪专访 36氪 该事件涉及机器人行业头部公司或知名平台的政策，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-16：新浪财经报道/收录《腰斩、炮轰、窗口指导，人形机器人开始渡劫》。",
        "2026-09-15：36氪报道/收录《人形机器人量产分水岭：双巨头跨万台大关 百亿独角兽加速追赶》。",
        "2026-09-13：新浪财经报道/收录《宇树科技暴涨暴跌后，监管收紧人形机器人IPO》。",
        "2026-09-10：新浪财经报道/收录《逐际动力“秘交”港股，人形机器人再冲IPO》。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 2 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从“为什么资本突然扎堆”切入，拆三件事：技术成熟度、工厂场景落地、上市窗口期。",
      "topic_value": "标题方向：人形机器人到底是产业爆发，还是资本抢跑。核心冲突：融资和上市热度很高，但真正量产、交付和商业回款仍需要验证。小胡讲法：从“为什么资本突然扎堆”切入，拆三件事：技术成熟度、工厂场景落地、上市窗口期。避坑：不要把演示视频等同于商业化，重点追问订单、成本和真实场景。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "中",
      "difficulty": "高",
      "verification_status": "多源确认",
      "verification_note": "已有至少两个媒体渠道覆盖，可作为较稳定候选。",
      "media_channel_count": 2,
      "media_channels": "36氪、新浪财经",
      "media_items": [
        {
          "source": "新浪财经",
          "title": "宇树科技暴涨暴跌后，监管收紧人形机器人IPO",
          "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE0yVzRpUjBQeTVJQkw4LVV4bnVKZUtucVpDMTNGNnRIOUc2RjQ0RThmek50X2hqYkpORm1hRGFlMFZ4VU1vR2ItNXNxTlZINDlQbVZOQ3Z6YW9yd3VXQTNyaXFfN2h5TmhyRFNTNU5Ua2M?oc=5",
          "date": "2026-09-13"
        },
        {
          "source": "36氪",
          "title": "人形机器人量产分水岭：双巨头跨万台大关 百亿独角兽加速追赶",
          "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9YcFFmbG5neXlZcDE3SURMLWt0SGtLMm1Eb1V5anVXQzk2UEZHZHZtbEZHYXVsZHF0RjF5bTQtODVEMXl5VUtaTnhOOHZOQ3dscEFj?oc=5",
          "date": "2026-09-15"
        },
        {
          "source": "36氪",
          "title": "1万台工业机器人：融资10亿",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1NNVRRX3ZDc1M4RFhLVVpHTmhSTVIwcmptWl96Y1lwdXpNNUVlaEo2aUt3dGpOTFRUbWprcnJ4d2UyVU1rb3h2Y3JTb3BVQQ?oc=5",
          "date": "2026-09-07"
        },
        {
          "source": "新浪财经",
          "title": "逐际动力“秘交”港股，人形机器人再冲IPO",
          "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFB3eGhZbHRHVng5cm9jQWxIbGZxbW51aEQxNlNVRGFBYnZiWWZfcHhreUhZOXlVMHRzNE90NHB0NGpaOFR1bDV4X05LVFd0SFB2V01ELXRYWDBJWnpzNFVZdFF5RTFPTVY0SVhCUEg5dTQ?oc=5",
          "date": "2026-09-10"
        },
        {
          "source": "36氪",
          "title": "人形机器人IPO风声趋紧：刚敲钟CEO炮轰同行“虚假收入”透支行业",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTFBXaDZ5SU9zTWNaa3IxOGxRRUtvQ2E0WDE2OTdlODNlQmxFTGtLMEFrZGlEVWtLUEJGWlFjcF9kU0h0bjloMmppY1V5R25nZw?oc=5",
          "date": "2026-09-09"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 32,
      "confidence_reason": "置信度 32/100，依据：2 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 5.1,
      "businessValue": 9.4,
      "controversy": 5.7,
      "longevity": 6.2,
      "fit": 6.1,
      "volume": "长",
      "note": "待核查来源：新浪财经: https://news.google.com/rss/articles/CBMicEFVX3lxTE0yVzRpUjBQeTVJQkw4LVV4bnVKZUtucVpDMTNGNnRIOUc2RjQ0RThmek50X2hqYkpORm1hRGFlMFZ4VU1vR2ItNXNxTlZINDlQbVZOQ3Z6YW9yd3VXQTNyaXFfN2h5TmhyRFNTNU5Ua2M?oc=5 | 36氪: https://news.google.com/rss/articles/CBMiU0FVX3lxTE9YcFFmbG5neXlZcDE3SURMLWt0SGtLMm1Eb1V5anVXQzk2UEZHZHZtbEZHYXVsZHF0RjF5bTQtODVEMXl5VUtaTnhOOHZOQ3dscEFj?oc=5 | 36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE1NNVRRX3ZDc1M4RFhLVVpHTmhSTVIwcmptWl96Y1lwdXpNNUVlaEo2aUt3dGpOTFRUbWprcnJ4d2UyVU1rb3h2Y3JTb3BVQQ?oc=5"
    },
    {
      "title": "千亿估值的智能戒指，要去IPO了",
      "source": "36氪",
      "date": "2026-09-04",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "千亿估值的智能戒指，要去IPO了 36氪",
      "core_summary": "千亿估值的智能戒指，要去IPO了 36氪 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-04：36氪报道/收录《千亿估值的智能戒指，要去IPO了》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：千亿估值的智能戒指准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "千亿估值的智能戒指，要去IPO了",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5FNGVpV3RFUG5ZU0Job2NrN3RaWUFPcFowTkRVZm0yU0FLZ2ZSb0FteUVfSG1DVWlwcERKN0pJSlFPcDBnYzNJOUhaN1A0dw?oc=5",
          "date": "2026-09-04"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 2.1,
      "businessValue": 7.5,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE5FNGVpV3RFUG5ZU0Job2NrN3RaWUFPcFowTkRVZm0yU0FLZ2ZSb0FteUVfSG1DVWlwcERKN0pJSlFPcDBnYzNJOUhaN1A0dw?oc=5"
    },
    {
      "title": "法国AI公司Mistral估值达240亿美元 三星与欧盟科技基金携手入局",
      "source": "新浪财经",
      "date": "2026-09-08",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "法国AI公司Mistral估值达240亿美元 三星与欧盟科技基金携手入局 新浪财经",
      "core_summary": "法国AI公司Mistral估值达240亿美元 三星与欧盟科技基金携手入局 新浪财经 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-08：新浪财经报道/收录《法国AI公司Mistral估值达240亿美元 三星与欧盟科技基金携手入局》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：法国AI公司Mistral估值达24...准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "新浪财经",
      "media_items": [
        {
          "source": "新浪财经",
          "title": "法国AI公司Mistral估值达240亿美元 三星与欧盟科技基金携手入局",
          "url": "https://news.google.com/rss/articles/CBMifEFVX3lxTE92SXdpZXpFWXk4VDhEbGZhdFhEOTFDUW0wdWJ6SzZNUEVNb3VjUjZPYjhraHlzSkt2eTNsTzhMZDhsN2h5TlFPSzkzUGtWYTRZcDlGdEhocXdXSE1MWnV4LXhoNUYxVmUxLXJpRnNhckJnYlV1eU1scUFJZlc?oc=5",
          "date": "2026-09-08"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 1.6,
      "businessValue": 7.0,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.6,
      "volume": "中",
      "note": "待核查来源：新浪财经: https://news.google.com/rss/articles/CBMifEFVX3lxTE92SXdpZXpFWXk4VDhEbGZhdFhEOTFDUW0wdWJ6SzZNUEVNb3VjUjZPYjhraHlzSkt2eTNsTzhMZDhsN2h5TlFPSzkzUGtWYTRZcDlGdEhocXdXSE1MWnV4LXhoNUYxVmUxLXJpRnNhckJnYlV1eU1scUFJZlc?oc=5"
    },
    {
      "title": "蚂蚁集团重押AI：一场输不起的估值突围战",
      "source": "新浪财经",
      "date": "2026-09-15",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "蚂蚁集团重押AI：一场输不起的估值突围战 手机新浪网",
      "core_summary": "蚂蚁集团重押AI：一场输不起的估值突围战 手机新浪网 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-15：新浪财经报道/收录《蚂蚁集团重押AI：一场输不起的估值突围战》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：蚂蚁集团重押AI准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "新浪财经",
      "media_items": [
        {
          "source": "新浪财经",
          "title": "蚂蚁集团重押AI：一场输不起的估值突围战",
          "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxOSkNFMFIxYm1IVEMtbVpMM2NqdEFBT1RIM0VsdGsxNHVEUEV4LXdFbVJDYllKMjJTQmdUOHBkTjZKZWV1T21VZ1ZiWG5vd2FzZ1JobVdybEJ6M1o1Ny1ZYUVEd3E0Qlc2ZDhPTFBUeU9vdDJQTnJ3WUNJUVF3aFA1dl84Snpfcy16cGJTc2VXREVGQQ?oc=5",
          "date": "2026-09-15"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 2.4,
      "businessValue": 7.0,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：新浪财经: https://news.google.com/rss/articles/CBMikgFBVV95cUxOSkNFMFIxYm1IVEMtbVpMM2NqdEFBT1RIM0VsdGsxNHVEUEV4LXdFbVJDYllKMjJTQmdUOHBkTjZKZWV1T21VZ1ZiWG5vd2FzZ1JobVdybEJ6M1o1Ny1ZYUVEd3E0Qlc2ZDhPTFBUeU9vdDJQTnJ3WUNJUVF3aFA1dl84Snpfcy16cGJTc2VXREVGQQ?oc=5"
    },
    {
      "title": "“全华班”打造的AI程序员，估值480亿美元",
      "source": "36氪",
      "date": "2026-09-12",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "“全华班”打造的AI程序员，估值480亿美元 36氪",
      "core_summary": "“全华班”打造的AI程序员，估值480亿美元 36氪 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-12：36氪报道/收录《“全华班”打造的AI程序员，估值480亿美元》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：“全华班”打造的AI程序员准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "“全华班”打造的AI程序员，估值480亿美元",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9fdVZudEVXdm5HSXZKaUM1TWZ5eGh2WFQyTXRyUG0tRVowX0I3T1RFWFFVR2RYb2NrLVhpTlctRGZzVXZCMzctNnFnOXc1dw?oc=5",
          "date": "2026-09-12"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 2.1,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE9fdVZudEVXdm5HSXZKaUM1TWZ5eGh2WFQyTXRyUG0tRVowX0I3T1RFWFFVR2RYb2NrLVhpTlctRGZzVXZCMzctNnFnOXc1dw?oc=5"
    },
    {
      "title": "“去宁化”担忧发酵？宁德时代A+H股总市值跌破1.5万亿元",
      "source": "界面新闻",
      "date": "2026-09-17",
      "industry": "新能源汽车行业",
      "type": "公司/行业动态",
      "summary": "“去宁化”担忧发酵？宁德时代A+H股总市值跌破1.5万亿元。该事件属于新能源汽车行业的公司/行业动态，需要结合公司动作、行业格局和商业模式变化判断选题价值。",
      "core_summary": "“去宁化”担忧发酵？宁德时代A+H股总市值跌破1.5万亿元。该事件属于新能源汽车行业的公司/行业动态，需要结合公司动作、行业格局和商业模式变化判断选题价值。 该事件涉及新能源汽车行业头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "时间未记录：界面新闻报道/收录《“去宁化”担忧发酵？宁德时代A+H股总市值跌破1.5万亿元》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从家庭买车决策切入，把价格、智驾、售后和品牌安全感放在一起讲，而不是做车型参数导购。",
      "topic_value": "标题方向：“去宁化”担忧发酵？宁德时代A+H股...这次变化，谁在为新能源车内卷买单。核心冲突：车企要销量、利润和智能化投入，消费者则担心刚买就降价、配置缩水或服务不稳定。小胡讲法：从家庭买车决策切入，把价格、智驾、售后和品牌安全感放在一起讲，而不是做车型参数导购。避坑：不要用单月销量或单款车型推断公司长期胜负，需区分官方披露、媒体报道和市场预期。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "界面新闻",
      "media_items": [
        {
          "source": "界面新闻",
          "title": "“去宁化”担忧发酵？宁德时代A+H股总市值跌破1.5万亿元",
          "url": "https://www.jiemian.com/article/15098433.html",
          "date": ""
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 1.4,
      "businessValue": 7.1,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：界面新闻: https://www.jiemian.com/article/15098433.html"
    },
    {
      "title": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”",
      "source": "36氪",
      "date": "2026-09-10",
      "industry": "全球科技与资本市场",
      "type": "公司/行业动态",
      "summary": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血” 36氪",
      "core_summary": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血” 36氪 该事件涉及全球科技与资本市场头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-10：36氪报道/收录《4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：4万亿美元准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE4wTWRQSnMxSmZBU2dlTmg3YVdHNzh5UDd4SDVCMjYwZDBRa3RFdEg0UjUyVVBOeHlwenJTSnREc0czX1lrTHc1cGZaVkhLQQ?oc=5",
          "date": "2026-09-10"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 2.1,
      "businessValue": 6.7,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE4wTWRQSnMxSmZBU2dlTmg3YVdHNzh5UDd4SDVCMjYwZDBRa3RFdEg0UjUyVVBOeHlwenJTSnREc0czX1lrTHc1cGZaVkhLQQ?oc=5"
    },
    {
      "title": "突发，OpenAI今年不上市了！",
      "source": "澎湃新闻",
      "date": "2026-09-16",
      "industry": "AI与芯片行业",
      "type": "公司/行业动态",
      "summary": "突发，OpenAI今年不上市了！ thepaper.cn",
      "core_summary": "突发，OpenAI今年不上市了！ thepaper.cn 该事件涉及AI与芯片行业头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-16：澎湃新闻报道/收录《突发，OpenAI今年不上市了！》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "用“谁付钱、谁省钱、谁被替代”三问切入，把复杂技术翻译成商业账本。",
      "topic_value": "标题方向：OpenAI的 AI 故事，最后要落到成本还是收入。核心冲突：市场愿意为 AI 想象力买单，但企业必须证明算力、芯片或模型投入能转化为订单、利润和用户效率。小胡讲法：用“谁付钱、谁省钱、谁被替代”三问切入，把复杂技术翻译成商业账本。避坑：不要展开过多技术细节，也不要把概念热度直接等同于商业化落地。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "澎湃新闻",
      "media_items": [
        {
          "source": "澎湃新闻",
          "title": "突发，OpenAI今年不上市了！",
          "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE84S3V5ZHRHWXhQcng4T0pqYXpWT1BQZTZYczVEX2dsTjFFVVBfVUtoMGxESG5yYmxjbWNlYWFId3FPbW9HTkpQMjJTT2I3MG9nS3RJOGUtMDAyNHNiemc?oc=5",
          "date": "2026-09-16"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 3.0,
      "businessValue": 6.6,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "中",
      "note": "待核查来源：澎湃新闻: https://news.google.com/rss/articles/CBMiXkFVX3lxTE84S3V5ZHRHWXhQcng4T0pqYXpWT1BQZTZYczVEX2dsTjFFVVBfVUtoMGxESG5yYmxjbWNlYWFId3FPbW9HTkpQMjJTT2I3MG9nS3RJOGUtMDAyNHNiemc?oc=5"
    },
    {
      "title": "比亚迪、吉利等新订单旺季前持续失速 “新势力”增长动能全面衰减 多间车企被外资大行看淡",
      "source": "新浪财经",
      "date": "2026-09-04",
      "industry": "新能源汽车行业",
      "type": "公司/行业动态",
      "summary": "比亚迪、吉利等新订单旺季前持续失速 “新势力”增长动能全面衰减 多间车企被外资大行看淡 新浪财经",
      "core_summary": "比亚迪、吉利等新订单旺季前持续失速 “新势力”增长动能全面衰减 多间车企被外资大行看淡 新浪财经 该事件涉及新能源汽车行业头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-04：新浪财经报道/收录《比亚迪、吉利等新订单旺季前持续失速 “新势力”增长动能全面衰减 多间车企被外资大行看淡》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从家庭买车决策切入，把价格、智驾、售后和品牌安全感放在一起讲，而不是做车型参数导购。",
      "topic_value": "标题方向：比亚迪这次变化，谁在为新能源车内卷买单。核心冲突：车企要销量、利润和智能化投入，消费者则担心刚买就降价、配置缩水或服务不稳定。小胡讲法：从家庭买车决策切入，把价格、智驾、售后和品牌安全感放在一起讲，而不是做车型参数导购。避坑：不要用单月销量或单款车型推断公司长期胜负，需区分官方披露、媒体报道和市场预期。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "新浪财经",
      "media_items": [
        {
          "source": "新浪财经",
          "title": "比亚迪、吉利等新订单旺季前持续失速 “新势力”增长动能全面衰减 多间车企被外资大行看淡",
          "url": "https://news.google.com/rss/articles/CBMi5AFBVV95cUxPTnJGdU8xakUwVU1XTVBNdVFpNmN1UVFEckxMOVhTUWcwVVcySXdzdzNvS25CRjBBelpmQUlndmFpOWFncnoyeGhpc0QxZGtVY1VBbFI3aDJjN3Vja0pwZkZtd0JWMjBXaG5qX0Y4TUJKaEdxenZWbEt0by1JYzVvWlduT25RTnRkZF9lYXhBQ3Ytc09oUTAwZVpSWEYzU0FEa2NRZnlHb2lZQVJfZDF0WmhySVRlYlpaSUlJU2RoWUR0dzczVTJPUDlsSWF4TUwxTUVfMFQwbE1pV3lSMFVwSnRwZ28?oc=5",
          "date": "2026-09-04"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 1.4,
      "businessValue": 6.6,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 6.1,
      "volume": "中",
      "note": "待核查来源：新浪财经: https://news.google.com/rss/articles/CBMi5AFBVV95cUxPTnJGdU8xakUwVU1XTVBNdVFpNmN1UVFEckxMOVhTUWcwVVcySXdzdzNvS25CRjBBelpmQUlndmFpOWFncnoyeGhpc0QxZGtVY1VBbFI3aDJjN3Vja0pwZkZtd0JWMjBXaG5qX0Y4TUJKaEdxenZWbEt0by1JYzVvWlduT25RTnRkZF9lYXhBQ3Ytc09oUTAwZVpSWEYzU0FEa2NRZnlHb2lZQVJfZDF0WmhySVRlYlpaSUlJU2RoWUR0dzczVTJPUDlsSWF4TUwxTUVfMFQwbE1pV3lSMFVwSnRwZ28?oc=5"
    },
    {
      "title": "燧原科技登陆科创板，国产AI芯片四小龙全部完成上市",
      "source": "新浪财经",
      "date": "2026-09-12",
      "industry": "AI与芯片行业",
      "type": "公司/行业动态",
      "summary": "燧原科技登陆科创板，国产AI芯片四小龙全部完成上市 手机新浪网",
      "core_summary": "燧原科技登陆科创板，国产AI芯片四小龙全部完成上市 手机新浪网 该事件涉及AI与芯片行业头部公司或知名平台的公司/行业动态，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-12：新浪财经报道/收录《燧原科技登陆科创板，国产AI芯片四小龙全部完成上市》。",
        "事件类型被归类为公司/行业动态，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "用“谁付钱、谁省钱、谁被替代”三问切入，把复杂技术翻译成商业账本。",
      "topic_value": "标题方向：燧原科技登陆科创板的 AI 故事，最后要落到成本还是收入。核心冲突：市场愿意为 AI 想象力买单，但企业必须证明算力、芯片或模型投入能转化为订单、利润和用户效率。小胡讲法：用“谁付钱、谁省钱、谁被替代”三问切入，把复杂技术翻译成商业账本。避坑：不要展开过多技术细节，也不要把概念热度直接等同于商业化落地。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "低",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "新浪财经",
      "media_items": [
        {
          "source": "新浪财经",
          "title": "燧原科技登陆科创板，国产AI芯片四小龙全部完成上市",
          "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFAxWHExN18yMWRqQVNMY0FueDBPUzE3ekhyTWViNE0yUmREaXFTMXVaV2c4TzZ0dWVLNko3d2tNUGdId0Z2bi1mb2lrdEtWdWxXMXRhMk0xX2xMdnVDSk1KUTRNbmhnQzZXV1VNZ0NKcU9xUTkzckhNT0ZsSE1rUQ?oc=5",
          "date": "2026-09-12"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 2.4,
      "businessValue": 6.6,
      "controversy": 5.0,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "中",
      "note": "待核查来源：新浪财经: https://news.google.com/rss/articles/CBMifkFVX3lxTFAxWHExN18yMWRqQVNMY0FueDBPUzE3ekhyTWViNE0yUmREaXFTMXVaV2c4TzZ0dWVLNko3d2tNUGdId0Z2bi1mb2lrdEtWdWxXMXRhMk0xX2xMdnVDSk1KUTRNbmhnQzZXV1VNZ0NKcU9xUTkzckhNT0ZsSE1rUQ?oc=5"
    },
    {
      "title": "甲酰胺风波去，Babycare上市起？",
      "source": "36氪",
      "date": "2026-09-14",
      "industry": "全球科技与资本市场",
      "type": "舆论",
      "summary": "甲酰胺风波去，Babycare上市起？ 36氪",
      "core_summary": "甲酰胺风波去，Babycare上市起？ 36氪 该事件涉及全球科技与资本市场头部公司或知名平台的舆论，会影响行业竞争格局、消费者体验或资本市场预期，适合作为本周商业热点持续观察。",
      "key_nodes": [
        "2026-09-14：36氪报道/收录《甲酰胺风波去，Babycare上市起？》。",
        "事件类型被归类为舆论，需要继续核对后续公开报道。"
      ],
      "social_opinions": [],
      "public_consensus": [
        "高赞评论样本不足，暂不归纳公众共识。"
      ],
      "public_controversies": [
        "高赞评论样本不足，暂不归纳主要争议。"
      ],
      "social_data_complete": false,
      "why_now": "本周至少 1 个媒体入口出现相关信息，适合先判断是否具备跨平台传播和商业解释空间。",
      "business_angle": "从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。",
      "topic_value": "标题方向：甲酰胺风波去准备上市，资本市场到底在买什么未来。核心冲突：超级独角兽的估值来自技术、用户规模和未来垄断想象，但上市会把故事拉回收入、利润、现金流和监管透明度。小胡讲法：从普通人熟悉的产品或创始人切入，再拆这家公司为什么急着或被迫走向资本市场，以及谁会为高估值买单。避坑：上市、估值和融资信息要区分官方披露、媒体报道和市场传闻，不把“考虑上市”讲成“已经上市”。高赞评论尚未补齐，评论区结论先留白，避免把媒体判断当成公众情绪。",
      "risk": "中",
      "difficulty": "中",
      "verification_status": "常规",
      "verification_note": "",
      "media_channel_count": 1,
      "media_channels": "36氪",
      "media_items": [
        {
          "source": "36氪",
          "title": "甲酰胺风波去，Babycare上市起？",
          "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5KSkV5MnRMdTR1bl9FamhJaHhtTEpwa3h0WFVScFM1QkdVVjZGUDBIRXVmcFMtdFpOdEdQOWhJeF81RWloOTAyaWo0eGlidw?oc=5",
          "date": "2026-09-14"
        }
      ],
      "big_v_count": 0,
      "big_v_highlights": "",
      "big_v_items": [],
      "video_source_count": 0,
      "video_items": [],
      "wechat_index": "",
      "confidence": 20,
      "confidence_reason": "置信度 20/100，依据：1 个媒体渠道，暂无大 V 提及录入，暂无视频源录入，微信指数未录入或未命中。",
      "public_interest": 1.3,
      "businessValue": 6.7,
      "controversy": 5.7,
      "longevity": 5.7,
      "fit": 5.6,
      "volume": "中",
      "note": "待核查来源：36氪: https://news.google.com/rss/articles/CBMiTkFVX3lxTE5KSkV5MnRMdTR1bl9FamhJaHhtTEpwa3h0WFVScFM1QkdVVjZGUDBIRXVmcFMtdFpOdEdQOWhJeF81RWloOTAyaWo0eGlidw?oc=5"
    }
  ],
  "rawItems": [
    {
      "source_name": "界面新闻",
      "title": "“去宁化”担忧发酵？宁德时代A+H股总市值跌破1.5万亿元",
      "url": "https://www.jiemian.com/article/15098433.html",
      "published": "",
      "summary": "",
      "source_weight": 1.0
    },
    {
      "source_name": "36氪",
      "title": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血”",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE4wTWRQSnMxSmZBU2dlTmg3YVdHNzh5UDd4SDVCMjYwZDBRa3RFdEg0UjUyVVBOeHlwenJTSnREc0czX1lrTHc1cGZaVkhLQQ?oc=5",
      "published": "2026-09-10",
      "summary": "4万亿美元，美国AI三巨头集体上市“抢钱”，华尔街流动性恐遭“抽血” 36氪",
      "source_weight": 1.05
    },
    {
      "source_name": "新浪财经",
      "title": "蚂蚁集团重押AI：一场输不起的估值突围战",
      "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxOSkNFMFIxYm1IVEMtbVpMM2NqdEFBT1RIM0VsdGsxNHVEUEV4LXdFbVJDYllKMjJTQmdUOHBkTjZKZWV1T21VZ1ZiWG5vd2FzZ1JobVdybEJ6M1o1Ny1ZYUVEd3E0Qlc2ZDhPTFBUeU9vdDJQTnJ3WUNJUVF3aFA1dl84Snpfcy16cGJTc2VXREVGQQ?oc=5",
      "published": "2026-09-15",
      "summary": "蚂蚁集团重押AI：一场输不起的估值突围战 手机新浪网",
      "source_weight": 0.95
    },
    {
      "source_name": "新浪财经",
      "title": "宇树科技暴涨暴跌后，监管收紧人形机器人IPO",
      "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE0yVzRpUjBQeTVJQkw4LVV4bnVKZUtucVpDMTNGNnRIOUc2RjQ0RThmek50X2hqYkpORm1hRGFlMFZ4VU1vR2ItNXNxTlZINDlQbVZOQ3Z6YW9yd3VXQTNyaXFfN2h5TmhyRFNTNU5Ua2M?oc=5",
      "published": "2026-09-13",
      "summary": "宇树科技暴涨暴跌后，监管收紧人形机器人IPO 手机新浪网",
      "source_weight": 0.95
    },
    {
      "source_name": "36氪",
      "title": "千亿估值的智能戒指，要去IPO了",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5FNGVpV3RFUG5ZU0Job2NrN3RaWUFPcFowTkRVZm0yU0FLZ2ZSb0FteUVfSG1DVWlwcERKN0pJSlFPcDBnYzNJOUhaN1A0dw?oc=5",
      "published": "2026-09-04",
      "summary": "千亿估值的智能戒指，要去IPO了 36氪",
      "source_weight": 1.05
    },
    {
      "source_name": "36氪",
      "title": "人形机器人量产分水岭：双巨头跨万台大关 百亿独角兽加速追赶",
      "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9YcFFmbG5neXlZcDE3SURMLWt0SGtLMm1Eb1V5anVXQzk2UEZHZHZtbEZHYXVsZHF0RjF5bTQtODVEMXl5VUtaTnhOOHZOQ3dscEFj?oc=5",
      "published": "2026-09-15",
      "summary": "人形机器人量产分水岭：双巨头跨万台大关 百亿独角兽加速追赶 36Kr",
      "source_weight": 1.05
    },
    {
      "source_name": "36氪",
      "title": "甲酰胺风波去，Babycare上市起？",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5KSkV5MnRMdTR1bl9FamhJaHhtTEpwa3h0WFVScFM1QkdVVjZGUDBIRXVmcFMtdFpOdEdQOWhJeF81RWloOTAyaWo0eGlidw?oc=5",
      "published": "2026-09-14",
      "summary": "甲酰胺风波去，Babycare上市起？ 36氪",
      "source_weight": 1.05
    },
    {
      "source_name": "澎湃新闻",
      "title": "突发，OpenAI今年不上市了！",
      "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE84S3V5ZHRHWXhQcng4T0pqYXpWT1BQZTZYczVEX2dsTjFFVVBfVUtoMGxESG5yYmxjbWNlYWFId3FPbW9HTkpQMjJTT2I3MG9nS3RJOGUtMDAyNHNiemc?oc=5",
      "published": "2026-09-16",
      "summary": "突发，OpenAI今年不上市了！ thepaper.cn",
      "source_weight": 1.0
    },
    {
      "source_name": "36氪",
      "title": "“全华班”打造的AI程序员，估值480亿美元",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9fdVZudEVXdm5HSXZKaUM1TWZ5eGh2WFQyTXRyUG0tRVowX0I3T1RFWFFVR2RYb2NrLVhpTlctRGZzVXZCMzctNnFnOXc1dw?oc=5",
      "published": "2026-09-12",
      "summary": "“全华班”打造的AI程序员，估值480亿美元 36氪",
      "source_weight": 1.05
    },
    {
      "source_name": "新浪财经",
      "title": "法国AI公司Mistral估值达240亿美元 三星与欧盟科技基金携手入局",
      "url": "https://news.google.com/rss/articles/CBMifEFVX3lxTE92SXdpZXpFWXk4VDhEbGZhdFhEOTFDUW0wdWJ6SzZNUEVNb3VjUjZPYjhraHlzSkt2eTNsTzhMZDhsN2h5TlFPSzkzUGtWYTRZcDlGdEhocXdXSE1MWnV4LXhoNUYxVmUxLXJpRnNhckJnYlV1eU1scUFJZlc?oc=5",
      "published": "2026-09-08",
      "summary": "法国AI公司Mistral估值达240亿美元 三星与欧盟科技基金携手入局 新浪财经",
      "source_weight": 0.95
    },
    {
      "source_name": "新浪财经",
      "title": "燧原科技登陆科创板，国产AI芯片四小龙全部完成上市",
      "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFAxWHExN18yMWRqQVNMY0FueDBPUzE3ekhyTWViNE0yUmREaXFTMXVaV2c4TzZ0dWVLNko3d2tNUGdId0Z2bi1mb2lrdEtWdWxXMXRhMk0xX2xMdnVDSk1KUTRNbmhnQzZXV1VNZ0NKcU9xUTkzckhNT0ZsSE1rUQ?oc=5",
      "published": "2026-09-12",
      "summary": "燧原科技登陆科创板，国产AI芯片四小龙全部完成上市 手机新浪网",
      "source_weight": 0.95
    },
    {
      "source_name": "新浪财经",
      "title": "比亚迪、吉利等新订单旺季前持续失速 “新势力”增长动能全面衰减 多间车企被外资大行看淡",
      "url": "https://news.google.com/rss/articles/CBMi5AFBVV95cUxPTnJGdU8xakUwVU1XTVBNdVFpNmN1UVFEckxMOVhTUWcwVVcySXdzdzNvS25CRjBBelpmQUlndmFpOWFncnoyeGhpc0QxZGtVY1VBbFI3aDJjN3Vja0pwZkZtd0JWMjBXaG5qX0Y4TUJKaEdxenZWbEt0by1JYzVvWlduT25RTnRkZF9lYXhBQ3Ytc09oUTAwZVpSWEYzU0FEa2NRZnlHb2lZQVJfZDF0WmhySVRlYlpaSUlJU2RoWUR0dzczVTJPUDlsSWF4TUwxTUVfMFQwbE1pV3lSMFVwSnRwZ28?oc=5",
      "published": "2026-09-04",
      "summary": "比亚迪、吉利等新订单旺季前持续失速 “新势力”增长动能全面衰减 多间车企被外资大行看淡 新浪财经",
      "source_weight": 0.95
    },
    {
      "source_name": "36氪",
      "title": "1万台工业机器人：融资10亿",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1NNVRRX3ZDc1M4RFhLVVpHTmhSTVIwcmptWl96Y1lwdXpNNUVlaEo2aUt3dGpOTFRUbWprcnJ4d2UyVU1rb3h2Y3JTb3BVQQ?oc=5",
      "published": "2026-09-07",
      "summary": "1万台工业机器人：融资10亿 36氪",
      "source_weight": 1.05
    },
    {
      "source_name": "新浪财经",
      "title": "逐际动力“秘交”港股，人形机器人再冲IPO",
      "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFB3eGhZbHRHVng5cm9jQWxIbGZxbW51aEQxNlNVRGFBYnZiWWZfcHhreUhZOXlVMHRzNE90NHB0NGpaOFR1bDV4X05LVFd0SFB2V01ELXRYWDBJWnpzNFVZdFF5RTFPTVY0SVhCUEg5dTQ?oc=5",
      "published": "2026-09-10",
      "summary": "逐际动力“秘交”港股，人形机器人再冲IPO 手机新浪网",
      "source_weight": 0.95
    },
    {
      "source_name": "36氪",
      "title": "人形机器人IPO风声趋紧：刚敲钟CEO炮轰同行“虚假收入”透支行业",
      "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTFBXaDZ5SU9zTWNaa3IxOGxRRUtvQ2E0WDE2OTdlODNlQmxFTGtLMEFrZGlEVWtLUEJGWlFjcF9kU0h0bjloMmppY1V5R25nZw?oc=5",
      "published": "2026-09-09",
      "summary": "人形机器人IPO风声趋紧：刚敲钟CEO炮轰同行“虚假收入”透支行业 36氪",
      "source_weight": 1.05
    }
  ]
};
